#!/usr/bin/env bash
# Bash script that generates a MySQL dump and creates a compressed archive out of it.
filename="$(date +"%d")-$(date +"%m")-$(date +"%Y").tar.gz"
sudo mysqldump --all-databases -u root --password="$1" > backup.sql
tar -czvf "$filename" backup.sql
